### ISSUE TITLE
ffip-split-window-horizontally - need to press enter before typing to live search

### ISSUE THREAD

**Issue by rofrol** [technomancy/find-file-in-project#116]
I wish there was option for `ffip-split-window-horizontally` (and same for `ffip-split-window-vertically`), so that I don't have to press `Enter` before typing to search.

It should work like `find-file-in-project` so that after running it, I can start typing to search.

**Comment by redguardtoo** [comment]
Say you got a 3 files,

module1.test.js
module2.test.js
container1.js

If you want to find `module2.test.js`, you could input `test` at first, the backend `gnu find` will find files whose name containing `test`. Then you can use ivy to filter the candidates. `test` is the first and irrevocable keyword.

The benefit is the display order of the first keyword in the candidate line has no impact on the other keywords in the same line.

Besides, it's much faster because the first keyword uses the `gnus find` to actually filter the result during first round. It has good performance on all operating systems (Windows, for example).

Personally I'd rather use `find-file-in-project-by-selected` instead of `find-file-in-project`.

`find-file-in-project` does not use cli program to filter the result. So it could too slow for big projects because using pure lisp to filter is really slow.

Many other plugins only use cli program to filter. So they are faster on macOS/Linux but extremely slow on Window because the overhead to start cli program on Windows is too high.

**Comment by rofrol** [comment]
So how can I use `find-file-in-project-by-selected` to open like `ffip-split-window-horizontally`?

Also is it possible to ommit this step with pressing `Enter`?

Also I see that I can run it like `(ffip-split-window-horizontally t)` to open in new window, but I cannot select to open vertically, right?

**Comment by redguardtoo** [comment]
Use latest version, `(setq ffip-split-window-without-asking-for-keyword t)`.

**Comment by rofrol** [comment]
Thanks. Works.
