### ISSUE TITLE
Per Project setup

### ISSUE THREAD

**Issue by habamax** [technomancy/find-file-in-project#48]
Hi,

From the README it is not clear when I should call that snippet of code:
```
;; if the full path of current file is under SUBPROJECT1 or SUBPROJECT2
;; OR if I'm reading my personal issue track document,
(when (ffip-current-full-filename-match-pattern-p "\\(/SUBPROJECT1\\|/SUBPROJECT2\\|issue-track.org\\)")
  ;; set the root directory into "~/projs/PROJECT_DIR"
  (setq-local ffip-project-root ("~/projs/PROJECT_DIR"))
  ;; well, I'm not interested in concatenated BIG js file or file in dist/
  (setq-local ffip-find-options "-not -size +64k -not -iwholename '*/dist/*'")
  ;; do NOT search files in below directories
  (setq-local ffip-prune-patterns '("*/.git/*" "*/.hg/*" "*/.svn/*" "*/node_modules/*" "*/bower_components/*")))
  ;; for this project, I'm only interested certain types of files
  (setq-local ffip-patterns '("*.html" "*.js" "*.css" "*.java" "*.xml" "*.js")))
```

Should it be hooked?

**Comment by habamax** [comment]
If this is not hooked, then it works for the first file I open under /SUBPROJECT1 and doesn't work for another under the same /SUBPROJECT1.

**Comment by redguardtoo** [comment]
ffip works out of the box in 99% cases.

The OPTIONAL setup is only needed if you want to override ffip's default setup. 

For example, ffip will automatically find the project root if you use git/mercurial/subversion, if project is not under these VCS, you need specify a project root manually.

**Comment by habamax** [comment]
The problem I would like to solve is to have per project ffip-prune-patterns and ffip-patterns.
Helm-projectile has .projectile file where you can add excludes -- sadly it doesn't work as I expect it to be. Exclusions don't work for nested directories.
Now I have tried ffip and didn't find the way to exclude directories and file-patterns. With the similar setup as showed in README prunes and patterns are appllied only to the first opened file in the project. After I open another file and issue M-x ffip I can see all excluded files in the list.

**Comment by redguardtoo** [comment]
here is sample:
`find . -name '*.js'`, you got `./sub/dir1/index.js`, reguard it as a string.
(setq-local ffip-prune-pattern '('*/sub/di*inde*')) will exclude that string because the prune pattern matches that string.

more samples for prune patterns:
to exclude a directory like .git/, use "*/.git/*", to exclude a file test.js, use "*/test.js", to exclude test.js under subdir1, use "*/subdir1/test.js". wildcard "*" means any string.

a directory or a file is just a string, your prune pattern will match that string exactly.

`ffip-current-full-filename-match-pattern-p` give you a chance to switch to a different project.

ffip and other commands should work out of the box, I've been using these commands for years.

If you still have problem, send me more details.

**Comment by redguardtoo** [comment]
I updated README, there is complete per-project setup you can paste into your ~/.emacs.d/init.el

**Comment by habamax** [comment]
So yes, there should be hook.
Basically in that hook one can read `ffip-project-root/.ffip` file and add prunes to `ffip-prune-patterns`.

I am not that kind of 'setup package by code it' person but if I wouldn't be able to get helm-projectile respect its excludings I will do it.

So this could be closed I guess.
Thanks.

**Comment by redguardtoo** [comment]
http://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

emacs has already supported the .ffip out of the box.

**Comment by habamax** [comment]
My bad! I forget there is dir-locals.el that works for a directory and subdirectories.
Thanks for pointing that out!

Setup by code is practical indeed but I prefer, if possible, to have project specific settings separated.
